# Generated by Django 3.1.12 on 2024-12-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('bibid', models.IntegerField()),
                ('itemid', models.IntegerField()),
                ('code_barre', models.CharField(max_length=255)),
                ('d_creation', models.DateField()),
                ('d_modif', models.DateField()),
                ('cote', models.CharField(max_length=255)),
                ('inventaire', models.CharField(max_length=255)),
                ('titre', models.TextField()),
                ('auteur', models.TextField(blank=True, null=True)),
                ('staff_note', models.TextField(blank=True, null=True)),
                ('isbn_a', models.CharField(blank=True, max_length=255, null=True)),
                ('item_class', models.CharField(max_length=255)),
                ('nb_page', models.CharField(max_length=255)),
                ('date_edition', models.CharField(max_length=4)),
                ('editeur', models.CharField(max_length=255)),
                ('prix', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Livres',
            },
        ),
    ]
