# Generated by Django 5.1.4 on 2024-12-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_libraryresource_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.IntegerField()),
                ('BIBID', models.IntegerField()),
                ('ITEMID', models.IntegerField()),
                ('code_barre', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('modif_date', models.DateField()),
                ('cote', models.CharField(max_length=255)),
                ('inventaire', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('staff_note', models.CharField(max_length=255)),
                ('isbn_a', models.CharField(max_length=255)),
                ('item_class', models.CharField(max_length=255)),
                ('nb_page', models.CharField(max_length=255)),
                ('date_edition', models.IntegerField()),
                ('editeur', models.CharField(max_length=255)),
                ('prix', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='LibraryResource',
        ),
    ]
